source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'tartarus', :path => '../../'
gem 'will_paginate', '>= 3.0.pre2'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :development, :test do
 gem "rspec-rails"
 gem 'rcov'
end

