development:
  logging_enabled: true
  logger_class: LoggedException 
  notifiers:
    mail:
      address: 
      sender: noreply@example.com 
      threshold: 10
test:
  logging_enabled: false
  logger_class: LoggedException
  notifiers:
    mail:
      address: 
      sender: noreply@example.com 
      threshold: 10
production:
  logging_enabled: true
  logger_class: LoggedException
  notifiers:
    mail:
      address: 
      sender: noreply@example.com 
      threshold: 10
